model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/usdr" # name of the logged metric which determines when model is improving
  save_top_k: 1 # 只保留 val/usdr 最高的一个，不再用 pick_best.py 二次挑选
  save_last: True # additionaly always save model from last epoch
  mode: "max" # can be "max" or "min"
  verbose: True
  dirpath: "checkpoints/"
  filename: "{epoch:02d}-{step}"

#all_epoch_checkpoint:
#  _target_: pytorch_lightning.callbacks.ModelCheckpoint
#  monitor: null
#  save_top_k: -1
#  save_last: False
#  verbose: False
#  dirpath: "checkpoints/all_epochs/"
#  filename: "epoch={epoch:02d}-step={step}"
#  every_n_epochs: 1
#  save_on_train_epoch_end: True
#
#early_stopping:
#  _target_: pytorch_lightning.callbacks.EarlyStopping
#  monitor: "val/sdr" # name of the logged metric which determines when model is improving
#  patience: 300 # how many epochs of not improving until training stops
#  mode: "max" # can be "max" or "min"
#  min_delta: 0.05 # minimum change in the monitored metric needed to qualify as an improvement
